"""Game data models."""
from __future__ import annotations

import uuid
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


def uid() -> str:
    """Generate a short unique id, shared across all modules."""
    return uuid.uuid4().hex[:12]


# ── Enums ──────────────────────────────────────────────

class ScriptStyle(str, Enum):
    DETECTIVE = "detective"      # 正统侦探/悬疑
    DRAMA = "drama"              # 戏剧侦探/搞笑
    DISCOVER = "discover"        # 寻迹侦探/探索
    DESTINY = "destiny"          # 命运侦探/浪漫
    DREAM = "dream"              # 幻梦侦探/叙诡
    DIMENSION = "dimension"      # 赛博侦探/科幻
    DEATH = "death"              # 幽冥侦探/恐怖


class RoleAlignment(str, Enum):
    INNOCENT = "innocent"
    MURDERER = "murderer"


class GamePhase(str, Enum):
    STYLE_SELECT = "style_select"
    CHARACTER_SELECT = "character_select"
    GENERATING = "generating"
    ROLE_ASSIGN = "role_assign"
    ACT_1 = "act_1"
    ACT_2 = "act_2"
    ACT_3 = "act_3"
    VOTING = "voting"
    ENDING = "ending"


class MessageType(str, Enum):
    DM_NARRATION = "dm_narration"       # DM 叙述
    CHARACTER_SPEAK = "character_speak"  # 角色发言
    PLAYER_SPEAK = "player_speak"       # 玩家发言
    SYSTEM = "system"                   # 系统消息
    CLUE = "clue"                       # 线索发放
    CHOICE = "choice"                   # 选择题
    VOTE = "vote"                       # 投票


# ── Characters & Roles ─────────────────────────────────

class Character(BaseModel):
    """Platform character (from AI companion platform)."""
    id: str
    name: str
    avatar: str = ""
    personality: str = ""
    description: str = ""


class Role(BaseModel):
    """Script role generated by AI."""
    id: str
    name: str
    alignment: RoleAlignment
    background: str = ""
    secret: str = ""
    clues: list[str] = Field(default_factory=list)


class CharacterRoleMapping(BaseModel):
    """Maps a platform character to a script role."""
    character_id: str
    role_id: str
    is_player: bool = False


# ── Game Content ───────────────────────────────────────

class Clue(BaseModel):
    id: str
    title: str
    content: str
    act: int  # 1, 2, or 3
    revealed: bool = False


class ChoiceOption(BaseModel):
    id: str
    text: str
    is_correct: bool = False


class ChoiceQuestion(BaseModel):
    id: str
    question: str
    options: list[ChoiceOption]
    explanation: str = ""


class Act(BaseModel):
    act_number: int
    title: str
    narration: str = ""
    clues: list[Clue] = Field(default_factory=list)
    choices: list[ChoiceQuestion] = Field(default_factory=list)
    generated: bool = False


class Script(BaseModel):
    """The full generated script."""
    style: ScriptStyle
    title: str = ""
    prologue: str = ""
    acts: list[Act] = Field(default_factory=list)
    roles: list[Role] = Field(default_factory=list)
    truth: str = ""  # DM only: the full truth
    murderer_role_id: str = ""


# ── Chat Messages ──────────────────────────────────────

class ChatMessage(BaseModel):
    id: str = ""
    type: MessageType
    sender_id: str = ""       # character_id or "dm" or "system"
    sender_name: str = ""
    content: str = ""
    choices: Optional[ChoiceQuestion] = None
    timestamp: float = 0


# ── Game Session ───────────────────────────────────────

class GameSession(BaseModel):
    id: str
    phase: GamePhase = GamePhase.STYLE_SELECT
    style: Optional[ScriptStyle] = None
    characters: list[Character] = Field(default_factory=list)
    mappings: list[CharacterRoleMapping] = Field(default_factory=list)
    script: Optional[Script] = None
    messages: list[ChatMessage] = Field(default_factory=list)
    current_act: int = 0
    act_answered: int = 0  # choices answered in current act
    score: int = 0
    player_character_id: str = ""
